import http from 'http';
import serveHandler from 'serve-handler';
import { validateDirPath } from '../../utils';
import { YargsArgs } from '../../types/yargs';
import { logServerError, logServerListening, logRequest } from './serveutils';

/**
 * Starts a local, static HTTP server on the given port with the given root
 * directory.
 *
 * @param argv - arguments as an object generated by yargs
 * @param argv.root - The root directory path string
 * @param argv.port - The server port
 */
export async function serve(argv: YargsArgs): Promise<void> {

  const { port, root } = argv;

  await validateDirPath(root as string, true);

  console.log(`\nStarting server...`);

  const server = http.createServer(async (req, res) => {
    await serveHandler(req, res, {
      public: root as string,
    });
  });

  server.listen({ port }, () => logServerListening(port));

  server.on('request', (request) => logRequest(request));

  server.on('error', (error) => logServerError(error, argv.port));

  server.on('close', () => {
    console.log('Server closed');
    process.exit(1);
  });
}
