import http from 'http';
import serveHandler from 'serve-handler';
import { logError, validateDirPath } from '../../utils';
import { YargsArgs } from '../../types/yargs';

/**
 * Starts a local, static HTTP server on the given port with the given root
 * directory.
 *
 * @param argv - arguments as an object generated by yargs
 * @param argv.root - The root directory path string
 * @param argv.port - The server port
 */
export async function serve(argv: YargsArgs): Promise<void> {

  const { port, root } = argv;

  await validateDirPath(root as string, true);

  console.log(`\nStarting server...`);

  const server = http.createServer(async (req, res) => {
    await serveHandler(req, res, {
      public: root as string,
    });
  });

  console.log(server);

  server.listen({ port }, () => logServerListening(port));

  server.on('request', (request) => logRequest(request));

  server.on('error', (error) => logServerError(error));

  server.on('close', () => {
    console.log('Server closed');
    process.exit(1);
  });

  function logServerListening(portInput: number) {
    console.log(`Server listening on: http://localhost:${portInput}`);
  }

  function logRequest(requestInput: Record<string, unknown>) {
    console.log(`Handling incoming request for: ${requestInput.url}`);
  }

  function logServerError(err: Error) {
    console.log((err as any).code);
    if ((err as any).code === 'EADDRINUSE') {
      logError(`Server error: Port ${port} already in use.`);
    } else {
      logError(`Server error: ${err.message}`, err);
    }
    process.exit(1);
  }
}
